### ISSUE TITLE
Array bound problem in datagen.cc

### ISSUE THREAD

**Issue by rcy17** [ypluo/TLBtree#3]
Hello, I'm trying to run workload generated by `/Single/test/gen.sh`, but when runing `workload1.txt` (Random RO) I got output:
```
somthing not found
```
With some debugging codes added, I found an impossible line in `workload1.txt`:
```
0 0
```
After some more digging, I believe codes below caused the bug

https://github.com/ypluo/TLBtree/blob/8f95ad79bc994b06907dbad3a26a1fd8772c446e/Single/test/datagen.cc#L115-L129

According to cppreference for uniform_int_distribution (https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution) and some simple test for zipfian_int_distribution, I found both distributions parameters a, b means **[a, b]** instead of **[a, b)**, for which `idx1_dist(0, scale);` may lead to a return of `scale` and the bug appear for index out of bound.
It seems that modifying `scale` to `scale - 1` can fix it.

**Comment by ypluo** [comment]
Thanks a lot for your mindful work. I have fixed this in the lastested version.
